# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Linter and Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  buildtest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv sync --dev --system
    - name: Lint with ruff
      run: |
        # Apply the linting
        ruff check
    - name: Test with pytest
      run: |
        # Run test and save coverage
        coverage run -m pytest test/
    - name: Generate coverage report
      run: |
        # Generate the coverage report
        coverage report > coverage.txt
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: test-coverage-report
        path: coverage.txt